apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
data:
  address: "YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xOjU2NzIK"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: producer-program
spec:
  template:
    metadata:
      labels:
        app: producer-program
    spec:
      restartPolicy: Never
      containers:
        - name: producer-program
          image: ghcr.io/kedify/blog05-python-producer-program:latest
          env:
            - name: MESSAGE_COUNT
              value: "15"
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: address
