apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: producer-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/moraesv/kubernetes"
    targetRevision: HEAD
    path: apps/producer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated: {}
