apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: production
spec:
  project: default
  source:
    repoURL: "https://github.com/moraesv/kubernetes"
    targetRevision: HEAD
    path: rabbitmq
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated: {}
