apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          ports:
            - containerPort: 5672
            - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
spec:
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: amqp
      nodePort: 30672
    - protocol: TCP
      port: 15672
      targetPort: 15672
      name: management
      nodePort: 30673
  type: NodePort
