apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: result-analyzer-program
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/moraesv/kubernetes"
    targetRevision: HEAD
    path: scaling-project/result-analyzer-program
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated: {}
